package com.nutribite.ai.recipe.service;
import com.nutribite.ai.model.User; import com.nutribite.ai.model.enums.DietType; import com.nutribite.ai.nutrition.model.MealType; import com.nutribite.ai.recipe.dto.*; import com.nutribite.ai.recipe.entity.*; import com.nutribite.ai.recipe.repository.*; import com.nutribite.ai.repository.UserRepository; import lombok.RequiredArgsConstructor; import org.springframework.data.domain.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.util.*;
@Service @RequiredArgsConstructor @Transactional
public class RecipeServiceImpl implements RecipeService {
 private final RecipeRepository recipes; private final FavoriteRepository favorites; private final UserRepository users;
 private User user(){String email=Objects.requireNonNull(org.springframework.security.core.context.SecurityContextHolder.getContext().getAuthentication()).getName(); return users.findByEmail(email).orElseThrow(()->new RuntimeException("User not found"));}
 private Pageable page(int p,int s){return PageRequest.of(Math.max(0,p),Math.min(Math.max(1,s),50),Sort.by("title").ascending());}
 private RecipeResponse map(Recipe r){User u=user(); boolean fav=favorites.existsByUserAndRecipe(u,r); List<RecipeResponse.Ingredient> ing=r.getIngredients().stream().map(i->RecipeResponse.Ingredient.builder().id(i.getId()).name(i.getName()).quantity(i.getQuantity()).unit(i.getUnit()).build()).toList(); return RecipeResponse.builder().id(r.getId()).title(r.getTitle()).description(r.getDescription()).instructions(r.getInstructions()).imageUrl(r.getImageUrl()).prepMinutes(r.getPrepMinutes()).cookMinutes(r.getCookMinutes()).servings(r.getServings()).mealType(r.getMealType()).dietType(r.getDietType()).calories(r.getCalories()).protein(r.getProtein()).carbs(r.getCarbs()).fat(r.getFat()).fiber(r.getFiber()).favorite(fav).createdAt(r.getCreatedAt()).ingredients(ing).build();}
 public Page<RecipeResponse> list(String q,MealType m,DietType d,int p,int s){Page<Recipe> x; Pageable pg=page(p,s); if(q!=null&&!q.isBlank()) x=recipes.findByTitleContainingIgnoreCase(q.trim(),pg); else if(m!=null&&d!=null)x=recipes.findByMealTypeAndDietType(m,d,pg); else if(m!=null)x=recipes.findByMealType(m,pg); else if(d!=null)x=recipes.findByDietType(d,pg); else x=recipes.findAll(pg); return x.map(this::map);}
 public RecipeResponse get(Long id){return map(recipes.findById(id).orElseThrow(()->new RuntimeException("Recipe not found: "+id)));}
 private Recipe apply(RecipeRequest r,Recipe entity){entity.setTitle(r.getTitle());entity.setDescription(r.getDescription());entity.setInstructions(r.getInstructions());entity.setImageUrl(r.getImageUrl());entity.setPrepMinutes(r.getPrepMinutes());entity.setCookMinutes(r.getCookMinutes());entity.setServings(r.getServings());entity.setMealType(r.getMealType());entity.setDietType(r.getDietType());entity.setCalories(r.getCalories());entity.setProtein(r.getProtein());entity.setCarbs(r.getCarbs());entity.setFat(r.getFat());entity.setFiber(r.getFiber());List<RecipeIngredient> list=new ArrayList<>();if(r.getIngredients()!=null)for(var i:r.getIngredients()) list.add(RecipeIngredient.builder().name(i.getName()).quantity(i.getQuantity()).unit(i.getUnit()).build());entity.replaceIngredients(list);return entity;}
 public RecipeResponse create(RecipeRequest r){return map(recipes.save(apply(r,Recipe.builder().build())));}
 public RecipeResponse update(Long id,RecipeRequest r){Recipe x=recipes.findById(id).orElseThrow(()->new RuntimeException("Recipe not found: "+id));return map(recipes.save(apply(r,x)));}
 public void delete(Long id){recipes.delete(recipes.findById(id).orElseThrow(()->new RuntimeException("Recipe not found: "+id)));}
 public RecipeResponse favorite(Long id){Recipe r=recipes.findById(id).orElseThrow(()->new RuntimeException("Recipe not found: "+id));User u=user(); if(!favorites.existsByUserAndRecipe(u,r)) favorites.save(RecipeFavorite.builder().user(u).recipe(r).build()); return map(r);}
 public void unfavorite(Long id){Recipe r=recipes.findById(id).orElseThrow(()->new RuntimeException("Recipe not found: "+id));favorites.findByUserAndRecipe(user(),r).ifPresent(favorites::delete);}
 public Page<RecipeResponse> favorites(int p,int s){List<RecipeResponse> list=favorites.findByUserOrderByCreatedAtDesc(user()).stream().map(x->map(x.getRecipe())).toList(); int from=Math.min(Math.max(0,p)*Math.min(Math.max(1,s),50),list.size());int to=Math.min(from+Math.min(Math.max(1,s),50),list.size());List<RecipeResponse> sub=list.subList(from,to);return new PageImpl<>(sub, page(p,s), list.size());}
}
