package com.nutribite.ai.tracking.service;
import com.nutribite.ai.model.User; import com.nutribite.ai.profile.entity.UserProfile; import com.nutribite.ai.profile.repository.UserProfileRepository; import com.nutribite.ai.repository.UserRepository; import com.nutribite.ai.tracking.dto.*; import com.nutribite.ai.tracking.entity.*; import com.nutribite.ai.tracking.repository.*; import lombok.RequiredArgsConstructor; import org.springframework.security.core.context.SecurityContextHolder; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.time.*; import java.util.*;
@Service @RequiredArgsConstructor @Transactional public class TrackingServiceImpl implements TrackingService { private final UserRepository users; private final UserProfileRepository profiles; private final WaterLogRepository waters; private final WeightLogRepository weights;
 private User user(){String e=SecurityContextHolder.getContext().getAuthentication().getName();return users.findByEmail(e).orElseThrow(()->new RuntimeException("User not found"));}
 public WaterLogResponse addWater(WaterLogRequest r){WaterLog x=WaterLog.builder().user(user()).amountLiters(r.getAmountLiters()).loggedAt(r.getLoggedAt()).note(r.getNote()).build();return map(waters.save(x));}
 public List<WaterLogResponse> waterToday(){LocalDate d=LocalDate.now();return waters.findByUserAndLoggedAtBetweenOrderByLoggedAtDesc(user(),d.atStartOfDay(),d.plusDays(1).atStartOfDay()).stream().map(this::map).toList();}
 public WaterTodayResponse waterSummary(){User u=user();LocalDate d=LocalDate.now();double consumed=Optional.ofNullable(waters.sumBetween(u,d.atStartOfDay(),d.plusDays(1).atStartOfDay())).orElse(0.0);double goal=profiles.findByUser(u).map(UserProfile::getDailyWaterGoal).orElse(0.0);return WaterTodayResponse.builder().goalLiters(goal).consumedLiters(round(consumed)).remainingLiters(round(Math.max(0,goal-consumed))).build();}
 public void deleteWater(Long id){WaterLog x=waters.findByIdAndUser(id,user()).orElseThrow(()->new RuntimeException("Water log not found"));waters.delete(x);}
 public WeightLogResponse addWeight(WeightLogRequest r){User u=user();LocalDate date=r.getLoggedOn()==null?LocalDate.now():r.getLoggedOn();WeightLog x=weights.findByUserAndLoggedOn(u,date).orElse(WeightLog.builder().user(u).loggedOn(date).build());x.setWeightKg(r.getWeightKg());x.setNote(r.getNote());WeightLog saved=weights.save(x);profiles.findByUser(u).ifPresent(p->p.setWeightKg(r.getWeightKg()));return map(saved);}
 public WeightLogResponse currentWeight(){return weights.findFirstByUserOrderByLoggedOnDesc(user()).map(this::map).orElseGet(()->profiles.findByUser(user()).filter(p->p.getWeightKg()!=null).map(p->WeightLogResponse.builder().weightKg(p.getWeightKg()).loggedOn(LocalDate.now()).build()).orElseThrow(()->new RuntimeException("No weight recorded")));}
 public List<WeightLogResponse> weightHistory(){return weights.findByUserOrderByLoggedOnDesc(user()).stream().map(this::map).toList();}
 public void deleteWeight(Long id){WeightLog x=weights.findByIdAndUser(id,user()).orElseThrow(()->new RuntimeException("Weight log not found"));weights.delete(x);}
 private WaterLogResponse map(WaterLog x){return WaterLogResponse.builder().id(x.getId()).amountLiters(x.getAmountLiters()).loggedAt(x.getLoggedAt()).note(x.getNote()).build();}
 private WeightLogResponse map(WeightLog x){return WeightLogResponse.builder().id(x.getId()).weightKg(x.getWeightKg()).loggedOn(x.getLoggedOn()).note(x.getNote()).build();}
 private double round(double x){return Math.round(x*100.0)/100.0;}
}
