server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/NutriBite
spring.datasource.username=postgres
spring.datasource.password=977803

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

logging.level.root=WARN

jwt.secret=CHANGE_TO_A_LONG_RANDOM_SECRET
jwt.expiration=86400000