import { useState } from "react";
import { ArrowRight, Eye, EyeOff, Sparkles } from "lucide-react";
import { Link, useLocation, useNavigate } from "react-router-dom";
import Logo from "../components/Logo";
import { useAuth } from "../auth/AuthContext";

export default function Login() {
  const { login } = useAuth(); const navigate = useNavigate(); const location = useLocation();
  const [form, setForm] = useState({ email: "", password: "" }); const [show, setShow] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  async function submit(e) { e.preventDefault(); setBusy(true); setError(""); try { const result = await login({ email: form.email.trim(), password: form.password }); const from = location.state?.from?.pathname; navigate(from && from !== "/login" ? from : "/home", { replace: true, state: { openedFromLogin: true, profileComplete: result.profileComplete } }); } catch (err) { setError(err.message || "Unable to sign in."); } finally { setBusy(false); } }
  return <div className="auth-page"><section className="auth-visual"><div className="auth-brand"><Logo/></div><div className="auth-copy"><span className="eyebrow light">INDIAN FOOD · SMART NUTRITION</span><h1>Eat better.<br/><em>Live lighter.</em></h1><p>Indian recipes, personal nutrition and a camera-first Snap AI experience in one calm space.</p><div className="visual-pills"><span>Indian recipes</span><span>Personal insights</span><span>Snap AI</span></div></div><div className="auth-orbit"><span>NB</span><i/><i/><i/></div></section><section className="auth-panel"><div className="auth-card"><Logo compact/><span className="eyebrow">WELCOME BACK</span><h2>Sign in.</h2><p className="muted">Continue where you left off.</p>{error && <div className="form-error">{error}</div>}<form onSubmit={submit}><label>Email<input type="email" autoComplete="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} required/></label><label>Password<div className="password-field"><input type={show?"text":"password"} autoComplete="current-password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})} required/><button type="button" onClick={()=>setShow(v=>!v)} aria-label={show?"Hide password":"Show password"}>{show?<EyeOff size={18}/>:<Eye size={18}/>}</button></div></label><button className="primary-action full" disabled={busy}>{busy?"Signing in…":"Sign in"}<ArrowRight size={17}/></button></form><p className="switch">New to NutriBiteAI? <Link to="/register">Create an account</Link></p><div className="privacy-line"><Sparkles size={14}/> Your account stays protected by JWT authentication.</div></div></section></div>;
}
