import { useEffect, useState } from "react";
import { Search, SlidersHorizontal, Sparkles } from "lucide-react";
import AppShell from "../components/AppShell";
import RecipeCard from "../components/RecipeCard";
import LoadingState from "../components/LoadingState";
import ErrorState from "../components/ErrorState";
import { foodApi } from "../api/foodApi";

const mealFilters=["ALL","BREAKFAST","LUNCH","DINNER","SNACK"];
export default function Recipes(){const [query,setQuery]=useState("");const [meal,setMeal]=useState("ALL");const [foods,setFoods]=useState([]);const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [selected,setSelected]=useState(null);
  async function load(){setLoading(true);setError("");try{const data=meal==="ALL"?await foodApi.lowCalorie():await foodApi.byMeal(meal);setFoods(Array.isArray(data)?data:[]);}catch(e){setError(e.message||"Could not load the food library.");}finally{setLoading(false);}}
  useEffect(()=>{load();},[meal]);
  async function search(){if(!query.trim()){load();return;}setLoading(true);setError("");try{const data=await foodApi.search(query.trim());setFoods(Array.isArray(data)?data:[]);}catch(e){setError(e.message||"Could not search the food library.");}finally{setLoading(false);}}
  const visible=foods.filter(f=>meal==="ALL"||f.mealType===meal);return <AppShell><div className="page recipes-page"><header className="section-head"><div><span className="eyebrow">DISCOVER / INDIA</span><h1>Food that feels familiar.</h1><p>Browse food records served by the NutriBiteAI backend. No fabricated recipe data.</p></div><div className="recipes-badge"><Sparkles size={16}/><span>Indian-first library</span></div></header><section className="recipe-toolbar"><form className="search-box" onSubmit={e=>{e.preventDefault();search();}}><Search size={18}/><input placeholder="Search dosa, paneer, roti…" value={query} onChange={e=>setQuery(e.target.value)}/><button type="submit">Search</button></form><button className="filter-button"><SlidersHorizontal size={17}/> Filters</button></section><div className="filter-row">{mealFilters.map(f=><button key={f} className={meal===f?"active":""} onClick={()=>setMeal(f)}>{f.replaceAll("_"," ")}</button>)}</div>{loading?<LoadingState label="Loading food library"/>:error?<ErrorState title="Food library unavailable" message={error} onRetry={load}/>:visible.length===0?<div className="empty-state"><Sparkles size={20}/><b>No food records found.</b><span>Try a broader search or another meal type.</span></div>:<div className="recipe-grid">{visible.map(food=><RecipeCard key={food.id||food.name} food={food} onOpen={setSelected}/>)}</div>}{selected&&<FoodDialog food={selected} onClose={()=>setSelected(null)}/>}</div></AppShell>;
}
function FoodDialog({food,onClose}){return <div className="modal-backdrop" role="dialog" aria-modal="true"><div className="food-dialog"><button className="modal-close" onClick={onClose}>×</button><span className="eyebrow">NUTRITION RECORD</span><h2>{food.name}</h2><p>{food.cuisine||"Indian cuisine"} · {food.mealType||"—"}</p><div className="food-stats"><div><b>{food.calories??"—"}</b><span>kcal</span></div><div><b>{food.protein??"—"}</b><span>protein g</span></div><div><b>{food.carbs??"—"}</b><span>carbs g</span></div><div><b>{food.fat??"—"}</b><span>fat g</span></div><div><b>{food.fiber??"—"}</b><span>fibre g</span></div></div><small>Serving: {food.servingSize??"—"} {food.servingUnit||"g"}. Values shown are the backend food-record fields.</small></div></div>}
