import { useState } from "react";
import { ArrowRight, Eye, EyeOff, Leaf } from "lucide-react";
import { Link, useNavigate } from "react-router-dom";
import Logo from "../components/Logo";
import { useAuth } from "../auth/AuthContext";

export default function Register() {
  const { register } = useAuth(); const navigate = useNavigate();
  const [form, setForm] = useState({ firstName: "", lastName: "", email: "", password: "", gender: "" }); const [confirm, setConfirm] = useState(""); const [show, setShow] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  async function submit(e) { e.preventDefault(); setError(""); if (form.password !== confirm) { setError("Passwords do not match."); return; } setBusy(true); try { await register(form); navigate("/login", { replace: true, state: { registered: true } }); } catch (err) { setError(err.message || "Unable to create your account."); } finally { setBusy(false); } }
  return <div className="auth-page"><section className="auth-visual register-visual"><Logo/><div className="auth-copy"><span className="eyebrow light">NUTRIBITEAI</span><h1>Make food<br/><em>work for you.</em></h1><p>Start with a simple account. We’ll use your profile later to personalize nutrition insights without forcing you into meal plans.</p><div className="auth-note"><Leaf size={17}/><span>Indian-first · profile-led · privacy-minded</span></div></div></section><section className="auth-panel"><div className="auth-card"><Logo compact/><span className="eyebrow">GET STARTED</span><h2>Create your account.</h2><p className="muted">Just the basics for now.</p>{error && <div className="form-error">{error}</div>}<form onSubmit={submit} className="form-grid register-form"><label>First name<input autoComplete="given-name" value={form.firstName} onChange={e=>setForm({...form,firstName:e.target.value})} required/></label><label>Last name<input autoComplete="family-name" value={form.lastName} onChange={e=>setForm({...form,lastName:e.target.value})}/></label><label className="span-2">Email<input type="email" autoComplete="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} required/></label><label>Password<div className="password-field"><input type={show?"text":"password"} autoComplete="new-password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})} required minLength={8}/><button type="button" onClick={()=>setShow(v=>!v)}>{show?<EyeOff size={18}/>:<Eye size={18}/>}</button></div></label><label>Confirm password<input type={show?"text":"password"} autoComplete="new-password" value={confirm} onChange={e=>setConfirm(e.target.value)} required/></label><label>Gender <span className="optional">optional</span><select value={form.gender} onChange={e=>setForm({...form,gender:e.target.value})}><option value="">Select</option><option value="MALE">Male</option><option value="FEMALE">Female</option><option value="OTHER">Other</option></select></label><div className="span-2"><button className="primary-action full" disabled={busy}>{busy?"Creating…":"Create account"}<ArrowRight size={17}/></button></div></form><p className="switch">Already have an account? <Link to="/login">Sign in</Link></p></div></section></div>;
}
